//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IderaTrialExperienceCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IderaTrialExperienceCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveBtnTitle {
            get {
                object obj = ResourceManager.GetObject("ActiveBtnTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Licenses.
        /// </summary>
        internal static string AddLicenseButtonDefaultText {
            get {
                return ResourceManager.GetString("AddLicenseButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_181 {
            get {
                object obj = ResourceManager.GetObject("Arrow_181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_24 {
            get {
                object obj = ResourceManager.GetObject("Arrow_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string BuyNowButtonDefaultText {
            get {
                return ResourceManager.GetString("BuyNowButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string CommunityButtonDefaultText {
            get {
                return ResourceManager.GetString("CommunityButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Community.
        /// </summary>
        internal static string CommunityPageButtonText {
            get {
                return ResourceManager.GetString("CommunityPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Idera Community Center to find additional resources, help topics and support from product experts..
        /// </summary>
        internal static string CommunityPageContent {
            get {
                return ResourceManager.GetString("CommunityPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Resources.
        /// </summary>
        internal static string CommunityPageTitle {
            get {
                return ResourceManager.GetString("CommunityPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap idera_30 {
            get {
                object obj = ResourceManager.GetObject("idera_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Idera_logo_new11 {
            get {
                object obj = ResourceManager.GetObject("Idera_logo_new11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://community.idera.com/forums/forum/products/general-product-forum/.
        /// </summary>
        internal static string IderaProductCommunityCenterUrl {
            get {
                return ResourceManager.GetString("IderaProductCommunityCenterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://trialcenter.idera.com.
        /// </summary>
        internal static string IderaTrialCenterUrl {
            get {
                return ResourceManager.GetString("IderaTrialCenterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you are not connected to the internet.You can try to open a browser and copy the link into the address box. 
        ///{0}.
        /// </summary>
        internal static string InternetConnectionErrorMessage {
            get {
                return ResourceManager.GetString("InternetConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Info.
        /// </summary>
        internal static string LicenseInfoButtonText {
            get {
                return ResourceManager.GetString("LicenseInfoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires: {0} days left
        ///Type: {1}
        ///Key: {2}
        ///Limit Code: {3}.
        /// </summary>
        internal static string LicenseInformationTextPattern {
            get {
                return ResourceManager.GetString("LicenseInformationTextPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_black {
            get {
                object obj = ResourceManager.GetObject("logo_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo1_ {
            get {
                object obj = ResourceManager.GetObject("logo1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maximize {
            get {
                object obj = ResourceManager.GetObject("Maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Regular {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Normalize {
            get {
                object obj = ResourceManager.GetObject("Normalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceSansPro_Bold {
            get {
                object obj = ResourceManager.GetObject("SourceSansPro_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TrialExpiredDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("TrialExpiredDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Trial.
        /// </summary>
        internal static string TrialExpiredDialog_ContinueToTrial_ButtonText {
            get {
                return ResourceManager.GetString("TrialExpiredDialog_ContinueToTrial_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Period has expired.
        /// </summary>
        internal static string TrialExpiredDialog_ExpiredTrialText {
            get {
                return ResourceManager.GetString("TrialExpiredDialog_ExpiredTrialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Help.
        /// </summary>
        internal static string TrialHelpButtonDefaultText {
            get {
                return ResourceManager.GetString("TrialHelpButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Help.
        /// </summary>
        internal static string TrialHelpPageButtonText {
            get {
                return ResourceManager.GetString("TrialHelpPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Idera&apos;s Trial Center to learn more about how to use the product and submit Questions to product experts to get up to speed fast..
        /// </summary>
        internal static string TrialHelpPageContent {
            get {
                return ResourceManager.GetString("TrialHelpPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Tips and Tricks.
        /// </summary>
        internal static string TrialHelpPageTitle {
            get {
                return ResourceManager.GetString("TrialHelpPageTitle", resourceCulture);
            }
        }
    }
}
